### ISSUE TITLE
Add support for using a custom HttpClient or HttpMessageHandler

### ISSUE THREAD

**Issue by fubar-coder** [StefH/WebDAV-Client#1]
It would be useful when you would be able to provide a custom HttpClient or HttpMessageHandler. This would allow the usage of the client in the following scenarios:

- Test for ASP.NET Core using the TestHost (with custom HttpMessageHandler or HttpClient)
- Usage on Android and iOS (with custom HttpMessageHandler)

**Comment by StefH** [comment]
Adding a custom HttpClient is possible. Do you also need another option to provide a custom HttpMessageHandler?

**Comment by fubar-coder** [comment]
Having both options would be nice, but I'd prefer the ability to use a custom `HttpMessageHandler`, because that would allow the usage of implementations like [NativeMessageHandler from Paul Betts](https://github.com/paulcbetts/ModernHttpClient).

**Comment by StefH** [comment]
I did update the constructors, please take a look if this is fine for you. (See latest code in this github project)

**Comment by fubar-coder** [comment]
Seems to be what I was looking for 👍 .

Just one thing, can you please add an additional net46 target which uses the `System.Net.Http` nuget package instead of the framework assemblies? I guess that System.Net.Http contains a bug fix for net46, because it supplies its own assembly (but uses the framework assemblies for net45).

**Comment by StefH** [comment]
You want the 4.3.0 versipn I guess? And only for 4.6 ?

**Comment by fubar-coder** [comment]
I think that a lower version might be fine. You can always upgrade yourself, but a downgrade gets difficult.

**Comment by StefH** [comment]
For now I just used 4.3.0

See NuGet from this feed:
https://www.myget.org/F/webdav-client/api/v3/index.json

If this one works fine; I will upload to real NuGet

**Comment by fubar-coder** [comment]
Works fine with my ASP.NET Core test project

**Comment by StefH** [comment]
Can you also chexk for a 462 project?

**Comment by fubar-coder** [comment]
Sure, but not today anymore.

**Comment by fubar-coder** [comment]
Running tests in a net462 project works too.

**Comment by StefH** [comment]
Uploaded to NuGet.org
