### ISSUE TITLE
PlatformNotSupportedException on Blazor Webassembly / WASM

### ISSUE THREAD

**Issue by OliverAbraham** [StefH/WebDAV-Client#11]
Hello,
I'm trying to get the Webdav client running on a .NET 6.0 blazor client app.
I am getting the mentioned exception on the Constructor of WebDavClient, saying 'Operation is not supported on this platform.'

I guess I have to add some switches to tell the library to use the browsers' httpClient.
Maybe the ones you gave in WebDAV-Client-Solution.sln.DotSettings. But don't know how?
Best regards
Oliver

**Comment by StefH** [comment]
@OliverAbraham 
I'll release a new vertsion with .NET 6 and 7 support, please test that NuGet version when it's available.

**Comment by StefH** [comment]
https://github.com/StefH/WebDAV-Client/pull/12
