### ISSUE TITLE
Need to initialize WebDavClient with two parameters

### ISSUE THREAD

**Issue by OliverAbraham** [StefH/WebDAV-Client#13]
Hi Stef,
thanks for your new release 1.1.2, I'm making progress.
Passing the HttpClient with the constructor, the former EPlatformNotSupportedException is gone.
But I need to pass the WebDavClientParams also, because I see no other way to pass BaseAddress and Credentials.

So I need a constructor:
public WebDavClient(HttpClient httpClient, WebDavClientParams @params)
or a similiar way (property etc).
Your method "ConfigureHttpClient" is private, so I cannot call it.

Best regards!
Oliver

**Comment by StefH** [comment]
The `WebDavClientParams` contains:
- BaseAddress
- Credentials

Why can't you use this constructor?

**Comment by OliverAbraham** [comment]
I am using this constructor. I need to pass that object to WebDavClient constructor.
But then it doesn't work in WASM because I *ALSO* need to pass the Http client instance.
(if I don't pass the Http client instance I am getting PlatformNotSupportedException).
I don't see a possibility to pass ClientParams AND Http client.

**Comment by StefH** [comment]
@OliverAbraham 

Which settings from the WebDavClientParams do you need which cannot be set on the http-client?

**Comment by OliverAbraham** [comment]
To make it work on Blazor, I need to pass WebDavClientParams with BaseAddress and Credentials, together with the httpClient instance from Blazor.
So it's the combination. One constructor only allows me to pass the client, one only the params.
I don't know if I can also set the params on the httpClient.
Best regards!

**Comment by StefH** [comment]
You can just create a HttpClient and provide the BaseAddress and the Credentials yourself, no need for ClientParams.

See
https://github.com/StefH/WebDAV-Client/blob/master/src/WebDAV-Client/WebDavClient.cs#L751

**Comment by OliverAbraham** [comment]
I'll check it out, thanks!
